### ISSUE TITLE
Provide Maven required version on Syndesis extensions examples

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-extensions#81]
currently Maven 3.5.2 is required when using extension-maven-plugin ( see https://github.com/syndesisio/syndesis/issues/2999 )

the error message when trying to use latest Maven version is quite cryptic:

`[ERROR] Failed to execute goal io.syndesis.extension:extension-maven-plugin:1.3.10:repackage-extension (default) on project syndesis-connector-irc: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.3.10:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@6bf0f70a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@5310e451: InvocationTargetException: Could not create new service instance: org/eclipse/aether/internal/impl/DefaultDependencyCollector: org.eclipse.aether.internal.impl.DefaultDependencyCollector -> [Help 1]`

By providing a requireMavenVersion enforcer rule, we will have a better message which by default is:
`Detected Maven Version: 3.6.1 is not in the allowed range [3.5,3.6).`
The message can even be customized if there are better proposals.

**Comment by squakez** [comment]
It seems that moving to latest Syndesis version fixes the problem. I've opened a generic request to [align to new versions](https://github.com/syndesisio/syndesis-extensions/blob/master/pom.xml#L31).

**Comment by apupier** [comment]
I tested with io.syndesis.extension:extension-maven-plugin:1.9.0.fuse-760020-redhat-00001 and i still have the same issue.
Can you precise which version you tried please?

**Comment by apupier** [comment]
ah seems it was added in 1.9.1 and 2.x https://github.com/syndesisio/syndesis/commit/f2fc423c4617fd2bb687f2a9e329995f083d762e

**Comment by squakez** [comment]
I tested with actual master, 2.0-SNAPSHOT

**Comment by squakez** [comment]
@apupier this issue was solved by #82 - may I close it?

**Comment by apupier** [comment]
> this issue was solved by #82 - may I close it?

yes, closing

**Comment by lucamaf** [comment]
I'm using branch 1.9.x and still experiencing the same issue.
If I switch to master it cannot find anywhere the version 2.0-SNAPSHOT ... any idea?

**Comment by oscerd** [comment]
You need to build Syndesis master locally @lucamaf

**Comment by squakez** [comment]
> I'm using branch 1.9.x and still experiencing the same issue.
> If I switch to master it cannot find anywhere the version 2.0-SNAPSHOT ... any idea?

With version 1.9.x you must still use 3.5.4: https://github.com/syndesisio/syndesis-extensions/blob/1.9.x/pom.xml#L212

**Comment by lucamaf** [comment]
thank you!
